FROM alpine:3.8

LABEL maintainer="Marc Ruiz -radykal- <radykal@radykal.com>"

RUN apk --update add openssl nginx

RUN mkdir -p {{ ssl_dir }} {{ nginx_root_dir }} /var/run

RUN openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
    -subj "/C=ES/L=Barcelona/O=Hu/CN={{ application_fqdn }}" \
    -keyout {{ ssl_key_file }}  -out {{ ssl_cert_file }}

COPY nginx.conf /etc/nginx/nginx.conf

COPY passwd /etc/nginx/passwd

COPY index.html {{ nginx_root_dir }}/index.html

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
