---

- name: Create security group to allow https from the world
  ec2_group:
    name: "public_https"
    description: Security Group for public https access
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: aws_security_group_public_https

- name: Management security group allows SSH access to the instance
  ec2_group:
    name: "management_ssh"
    description: Security Group for SSH access
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ management_cidr }}"
  register: aws_security_group_management_ssh
