---

- name: Launch ec2 instance
  ec2:
    key_name: "{{ aws_keypair_name }}"
    group_id:
      - "{{ aws_security_group_public_https.group_id }}"
      - "{{ aws_security_group_management_ssh.group_id }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_ami[aws_region] }}"
    wait: yes
    region: "{{ aws_region }}"
    instance_tags:
      Environment: "{{ deploy_environment }}"
      Name: "{{ deploy_environment }}-{{ application_name }}"
    exact_count: 1
    count_tag:
      Environment: "{{ deploy_environment }}"
      Name: "{{ deploy_environment }}-{{ application_name }}"
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_dns_name }}"
    groups: ec2launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to be available
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  with_items: "{{ ec2.instances }}"